version: 2.1

jobs:
  build:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: << parameters.ruby-version >>
      - image: redis:5.0.9
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install -j4
      - run: bundle exec rspec --profile 10

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: ["circleci/ruby:2.5.8", "circleci/ruby:2.6.6", "circleci/ruby:2.7.1"]
